export const PATHS = {
  AUTH_LOGIN: 'user/auth/login',
  AUTH_REGISTER: 'user/auth/register',
  AUTH_LOGOUT: 'user/auth/logout',
  LISTINGS: 'listings',
  NEW_LISTING: 'listings/new',
  LISTING_DETAIL: 'listings/:listingid',
  LISTING_PUBLISH: 'listings/publish/:listingid',
  LISTING_UNPUBLISH: 'listings/unpublish/:listingid',
  LISTING_REVIEW: 'listings/:listingid/review/:bookingid',
  BOOKINGS: 'bookings',
  NEW_BOOKING: 'bookings/new/:listingid',
  ACCEPT_BOOKING: 'bookings/accept/:bookingid',
  DECLINE_BOOKING: 'bookings/decline/:bookingid',
  DELETE_BOOKING: 'bookings/:bookingid',
};
